version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern_network

  backend:
    build: ./api
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myDatabase
      - PORT=4000
    depends_on:
      - mongodb
    networks:
      - mern_network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge

volumes:
  mongodb_data:
